### ISSUE TITLE
Compatibility with older Python versions

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/py-economic-complexity#1]
Hello! Nice to see this library for Economic Complexity is out.

I tried to install `economic-complexity` on my laptop, but I got an error because my current Python version is `Python 3.7.4`.

```
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.7.9,<4.0.0
ERROR: Could not find a version that satisfies the requirement economic-complexity (from versions: none)
ERROR: No matching distribution found for economic-complexity
```

Is it possible to be more flexible with the minimum version of Python?

A small typo mistake, in the README.md, in **Installation** section the library says that for installing, I need to do it via poetry

```
poetry install economic-complexity
```
However, the correct command should be `pip`
```
pip install economic-complexity
```

Should I send a PR for this one?

**Comment by frabarz** [comment]
fixed in release v0.1.1
